package tools;

import ds.Graph;
import models.Location;
import engines.DatabaseManager;
import engines.RouteEngine;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;


public class ExportRoute {

    public static Path exportRoute(int fromLocationId, int toLocationId) throws Exception {
        var locs = DatabaseManager.loadLocations();
        var roads = DatabaseManager.loadRoads();

        // Determine max node id
        int maxId = 0;
        for (int i = 0; i < locs.size(); i++) {
            Location l = locs.get(i);
            if (l.getLocationId() > maxId) maxId = l.getLocationId();
        }

        Graph graph = new Graph(maxId);
        for (int i = 0; i < locs.size(); i++) {
            graph.addLocation(locs.get(i));
        }
        for (int i = 0; i < roads.size(); i++) {
            graph.addRoad(roads.get(i));
        }

        RouteEngine.PathResult res = RouteEngine.dijkstra(graph, fromLocationId, toLocationId);

        // Build the point list once, then write it in two forms.
        List<String> points = new ArrayList<>();
        if (res != null && res.path != null) {
            for (int i = 0; i < res.path.size(); i++) {
                int nid = res.path.get(i);
                Location loc = null;
                for (int j = 0; j < locs.size(); j++) {
                    if (locs.get(j).getLocationId() == nid) { loc = locs.get(j); break; }
                }
                if (loc != null) {
                    points.add(String.format("  { \"lat\": %f, \"lon\": %f, \"name\": \"%s\" }",
                            loc.getLatitude(), loc.getLongitude(),
                            loc.getName().replace("\"", "\\\"")));
                }
            }
        }

        Path json = Path.of("web/campus_map/route.json");
        try (PrintWriter pw = new PrintWriter(new FileWriter(json.toFile()))) {
            if (points.isEmpty()) {
                pw.println("null");
            } else {
                pw.println("[");
                pw.println(String.join(",\n", points));
                pw.println("]");
            }
        }

        // The page is opened from disk (file://), where fetch() of a .json file
        // is blocked by the browser's same-origin rules. Writing the same data
        // as a script that assigns a global lets index.html simply include it,
        // which works from the filesystem with no server.
        Path js = Path.of("web/campus_map/route.js");
        try (PrintWriter pw = new PrintWriter(new FileWriter(js.toFile()))) {
            pw.println("// Generated by tools.ExportRoute - the actual RouteEngine.dijkstra path.");
            if (points.isEmpty()) {
                pw.println("var ROUTE = null;");
                pw.println("var ROUTE_SUMMARY = 'No route found between the selected locations.';");
            } else {
                pw.println("var ROUTE = [");
                pw.println(String.join(",\n", points));
                pw.println("];");
                pw.printf("var ROUTE_SUMMARY = '%d hops, %.3f km, %.2f min (Dijkstra)';%n",
                        res.path.size(), res.totalDistanceKm, res.totalTimeMin);
            }
        }

        return js;
    }
}
